language: python

jobs:
  include:
    - stage:
      name: "Test General"
      python:
      - "3.6"
      - "3.7"
      script:
        - echo "General test."
        - chmod +x Scripts/test_general.sh
        - bash ./Scripts/test_general.sh;
        - echo "Completed general tests";
    - stage:
      name: "Test Segmentation"
      python:
      - "3.6"
      - "3.7"
      script:
        - echo "Segementation test."
        - chmod +x Scripts/test_segmentation.sh
        - bash ./Scripts/test_segmentation.sh
        - echo "Completed segmentation tests"
    - stage:
      name: "Test UI"
      python:
      - "3.6"
      - "3.7"
      script:
        - echo "UI test."
        - chmod +x Scripts/test_ui.sh
        - bash ./Scripts/test_ui.sh
        - echo "Completed UI tests"
    - stage:
      name: "Test Merge"
      python:
      - "3.6"
      - "3.7"
      script:
        - echo "Testing merge."
        - chmod +x Scripts/test_merge.sh
        - bash ./Scripts/test_merge.sh
        - echo "Completed merge tests"